# Generated by Django 4.0.10 on 2023-03-28 00:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0002_lectures_type'),
        ('courses', '0003_alter_course_user_alter_studentcourses_course_and_more'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('accepted', 'accepted'), ('rejected', 'rejected')], default='rejected', max_length=20)),
                ('attendance_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attendance_requests', to='lecture.attendancerequest')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_att_course', to='courses.course')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_att_lecture', to='lecture.lectures')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attendance', to='students.student')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
