# Generated by Django 4.0.10 on 2023-06-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='week_no',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
