# Generated by Django 4.0.10 on 2023-03-28 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectures',
            name='type',
            field=models.CharField(choices=[('section', 'section'), ('lecture', 'lecture')], default='section', max_length=20, verbose_name='Type'),
        ),
    ]
