# Generated by Django 4.0.10 on 2023-06-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0002_lectures_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerequest',
            name='week_no',
            field=models.IntegerField(default=1),
        ),
    ]
