# Generated by Django 4.0.10 on 2023-03-12 07:37

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='title', unique=True)),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('banner_image', models.ImageField(default='/customer_default.jpg', upload_to='', verbose_name='banner image')),
                ('price', models.IntegerField(default=0, verbose_name='price')),
                ('user', models.ManyToManyField(related_name='doctors_assigned', to=settings.AUTH_USER_MODEL, verbose_name='course')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentCourses',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_to_students', to=settings.AUTH_USER_MODEL, verbose_name='courses_to_students')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_assigned', to=settings.AUTH_USER_MODEL, verbose_name='students_assigned')),
            ],
            options={
                'verbose_name': 'Course Assigned To Student',
                'verbose_name_plural': 'Courses Assigned To Students',
                'unique_together': {('user', 'course')},
            },
        ),
    ]
