# Generated by Django 4.0.10 on 2023-04-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_user_alter_studentcourses_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
        migrations.AddField(
            model_name='course',
            name='session_counts',
            field=models.IntegerField(default=12, verbose_name='session_counts'),
        ),
    ]
