# Generated by Django 4.0.10 on 2023-05-22 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_course_price_course_session_counts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(max_length=255, unique=True, verbose_name='description'),
        ),
    ]
