# Generated by Django 4.0.10 on 2023-03-11 21:35

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='Egypt', max_length=180, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(default='EG', max_length=2, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], default='male', max_length=20, verbose_name='gender'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'student'), ('doctor', 'doctor'), ('guest', 'guest')], default='student', max_length=20, verbose_name='User Type'),
        ),
    ]
